### ISSUE TITLE
Retrieve the results in Nested Groups

### ISSUE THREAD

**Issue by existeundelta** [hoonzis/fluentnest#13]
Hi!
in Nested Groups [https://github.com/hoonzis/fluentnest/wiki/FluentNest-wiki#nested-groups](url)

```
var result = client.Search<Car>(search => search.Aggregations(x => agg
    .SumBy<Car>(s => s.Price)
    .GroupBy(new List<string> {"engineType", "carType"})
));
```

How is the best way to retrieve the results?

Thanks
Xavi

**Comment by existeundelta** [comment]
I see 

 ```
var result =Client.Search<Car>(search =>search.Aggregations(agg => agg
                .SumBy(s => s.Price)
                .GroupBy(s => s.EngineType)
                .GroupBy(b => b.CarType)
            ));


            var carTypes = result.Aggs.GetGroupBy<Car>(x => x.CarType).ToList();
            Check.That(carTypes).HasSize(3);
            foreach (var carType in carTypes)
            {
                var engineTypes = carType.GetGroupBy<Car, CarType>(x => x.EngineType, k => new CarType
                {
                    Type = k.Key,
                    Price = k.GetSum<Car, decimal>(x => x.Price)
                }).ToList();

                Check.That(engineTypes).HasSize(2);
                Check.That(engineTypes.First().Price).Equals(20m);
            }
```

in the tests, but I don't know if there is a genèric way to do it?

**Comment by hoonzis** [comment]
Yes these are two different approaches. If you know the keys that you will group by, than you should take the first, typed approach, specifying each groupby(x=>x.fieldName) as you did above.

If you don't know the keys beforehead, than you will do the generic approach, but you have to repeat the keys in the GetResults, a simple test case is available here https://github.com/hoonzis/fluentnest/blob/master/FluentNest.Tests/GroupByTests.cs

    var result = Client.Search<Car>(search => search.Aggregations(agg => agg
		.SumBy(s => s.Price)
		.GroupBy(new List<string> { "engineType", "carType" })
	));

	var engineTypes = result.Aggs.GetGroupBy("engineType");
	Check.That(engineTypes).HasSize(2);

	foreach (var engineType in engineTypes)
	{
		var carTypes = engineType.GetGroupBy("carType");
		Check.That(carTypes).HasSize(3);
	}

**Comment by existeundelta** [comment]
thanks!

**Comment by hoonzis** [comment]
note that if you are in a completely dynamic situations with arbitrary number of keys to groupby, then you have to use recursion to unwrap the results. This can happen for instance if you are showing a tree to the user, groping by many fields and the depth (how many group by's he will see). Than you will endup with something like this:

```csharp
public class GenericBreakup
{
	public string Key { get; set; }
	public decimal Sum { get; set; }

	public IList<GenericBreakup> Children { get; set; }
}
	
public List<GenericBreakup> GetBreakup(List<string> keys)
{
	var sumOnSomeNotional = new AggregationDescriptor<StatisticRecord>().SumBy(s => s.TradedNotional);
	var reversedAndLowered = keys.Select(x => x.FirstCharacterToLower()).Reverse().ToList();
	var aggregations = reversedAndLowered.Aggregate(sumOnSomeNotional, (s, i) => s.GroupBy(i).SumBy(x => x.TradedNotional));

	var result =
		client.Search<StatisticRecord>(
			search =>
				search.Aggregations(x => aggregations));

	reversedAndLowered.Reverse();
	var firstKey = reversedAndLowered.First();
	var currentLevel = result.Aggs.GetGroupBy(firstKey);
	reversedAndLowered.RemoveAt(0);
	return GetBreakUp(currentLevel, reversedAndLowered);
}

public List<GenericBreakup> GetBreakUp(IEnumerable<KeyItem> currentLevel, List<string> childKeys)
{
	var generatedLevel = new List<GenericBreakup>();
	foreach (var keyItem in currentLevel)
	{
		var res = keyItem.AsContainer<StatisticRecord>();
		var breakup = new GenericBreakup
		{
			Key = keyItem.Key ?? keyItem.KeyAsString,
			Sum = Convert.ToDecimal(res.GetSum(x => x.TradedNotionalEur))
		};
		if (childKeys.Any())
		{
			var key = childKeys.First();

			breakup.Children = GetBreakUp(keyItem.GetGroupBy(key), childKeys.Pop());
		}

		generatedLevel.Add(breakup);
	}

	return generatedLevel;
}
```

I keep that example at hand

**Comment by existeundelta** [comment]
Thanks! for the moment I'm doing "hard coded" but I really want to evolve to something like this
