### ISSUE TITLE
Sorted Top Hits by Sum Metric

### ISSUE THREAD

**Issue by existeundelta** [hoonzis/fluentnest#14]
Is it possible? how would be? 

Thanks!

**Comment by existeundelta** [comment]
If i understand it, Sorted Top Hits, Returns based on DocCount? can be based on Sumby?

**Comment by hoonzis** [comment]
Hi,

I am not sure what you mean by "Paged Sorted" top hits. Currently the SortedTopHits method takes 4 parameters: the number of items to retrieve, the field used for sorting, the sorting order and a list of fields of each document to be retrieved. 

```csharp
           var result = Client.Search<User>(search => search.Aggregations(agg => agg
                // get 30 first users, sort by age. for each user retrieve name
                .SortedTopHits(40, x=>x.Name, SortType.Descending, x=>x.Name)
                .SumBy(x=>x.Age)
                .GroupBy(b => b.Nationality))
            );
```

This was for instance you can see the top 30 contributers to the total sumby for each group.
Is this what you mean?

**Comment by existeundelta** [comment]
mmm.. I think I'm doing something wrong, because I don't get a Top by bucket

**Comment by existeundelta** [comment]
May be I'm doing somthing wrong, because

```
.SumBy(x=>x.metric1)
.GroupBy(field1);
```

gives me the order by number of documents that match the filter and then by the Sum of the metric

and 

```
.SortedTopHits(40, x=>x.field1, SortType.Descending, x=>x.field1)
.SumBy(x=>x.metric1)
.GroupBy(field1);
```

gives me the same
