### ISSUE TITLE
properties names changed

### ISSUE THREAD

**Issue by marchanddesable** [hoonzis/fluentnest#17]
Hi,

I have some properties in upper cases, but when i do the request, the first letter of each properties is changed to lowercase... How can I avoid that?

Thanks.

**Comment by filpen** [comment]
Hello,

elasticsearch defaults field names to camelcase. Please take a look at this SO answer for possible solutions http://stackoverflow.com/a/32205530

**Comment by marchanddesable** [comment]
Hi,
I use Nest 2.0

I dont want to use the raw string option, I need lambda expressions.

I have this problem only when I use FluentNest, When I don't use it I don't have the camelcase problem.

My connectionString has the following properties:

connectionSettings.DefaultFieldNameInferrer(p => p);
connectionSettings.DefaultTypeNameInferrer(p => p.Name);

I think the options will be ignored..

In the index, the properties are in uppercase, like "MY_PROPERTY: blabla"
in the request it is transformed to "mY_PROPERTY" ...
Even if I set the option "DefaultFieldNameInferrer"

I try to create a dynamic request,
The code is like this:

QueryContainer filter = Filters.CreateFilter<objectModel>(f => f.UNIQ_KEY == "demo");

if (balbalba)
 filter = filter.AndFilteredOn<objectModel>(f => f.MY_FIELD == false);

if (balbala)
 filter = filter.AndFilteredOn<objectModel>(f => f.MY_FIELD == false);


                    var node = new Uri(BaseService.ELASTICSEARCH_ENDPOINT);
                    var connectionPool = new SniffingConnectionPool(new[] { node });
                    var connectionSettings = new ConnectionSettings(connectionPool)
                               .DefaultFieldNameInferrer(p => p)
                               .DefaultTypeNameInferrer(p => p.Name);

                    ElasticClient elasticClient = new ElasticClient(connectionSettings);

                    resp = elasticClient.Search<objectModel>
                        (s => s.Index(BaseService.ES_INDEX_NAME)
                            .Query(
                                q => q.ConstantScore
                                    (c => c.Filter(f => f.Bool(b => b.Must(m => filter))))
                                  )
                            .From(elemsToSkip)
                            .Take(maxResults)
                       )
                       .Hits
                       .Select(h => h.Source);

  List<objectModel> result = resp?.ToList();

**Comment by marchanddesable** [comment]
Hi,
I use Nest 2.0

I dont want to use the raw string option, I need lambda expressions.

I have this problem only when I use FluentNest, When I don't use it I don't have the camelcase problem.

My connectionString has the following properties:

connectionSettings.DefaultFieldNameInferrer(p => p);
connectionSettings.DefaultTypeNameInferrer(p => p.Name);

I think the options will be ignored..

In the index, the properties are in uppercase, like "MY_PROPERTY: blabla"
in the request it is transformed to "mY_PROPERTY" ...
Even if I set the option "DefaultFieldNameInferrer"

I try to create a dynamic request,
The code is like this:

``

QueryContainer filter = Filters.CreateFilter<objectModel>(f => f.UNIQ_KEY == "demo");

if (balbalba)
 filter = filter.AndFilteredOn<objectModel>(f => f.MY_FIELD == false);

if (balbala)
 filter = filter.AndFilteredOn<objectModel>(f => f.MY_FIELD == false);


                    var node = new Uri(BaseService.ELASTICSEARCH_ENDPOINT);
                    var connectionPool = new SniffingConnectionPool(new[] { node });
                    var connectionSettings = new ConnectionSettings(connectionPool)
                               .DefaultFieldNameInferrer(p => p)
                               .DefaultTypeNameInferrer(p => p.Name);

                    ElasticClient elasticClient = new ElasticClient(connectionSettings);

                    resp = elasticClient.Search<objectModel>
                        (s => s.Index(BaseService.ES_INDEX_NAME)
                            .Query(
                                q => q.ConstantScore
                                    (c => c.Filter(f => f.Bool(b => b.Must(m => filter))))
                                  )
                            .From(elemsToSkip)
                            .Take(maxResults)
                       )
                       .Hits
                       .Select(h => h.Source);

  List<objectModel> result = resp?.ToList();

**Comment by marchanddesable** [comment]
Hi,
I use Nest 2.0

I dont want to use the raw string option, I need lambda expressions.

I have this problem only when I use FluentNest, When I don't use it I don't have the camelcase problem.

My connectionString has the following properties:

connectionSettings.DefaultFieldNameInferrer(p => p);
connectionSettings.DefaultTypeNameInferrer(p => p.Name);

I think the options will be ignored..

In the index, the properties are in uppercase, like "MY_PROPERTY: blabla"
in the request it is transformed to "mY_PROPERTY" ...
Even if I set the option "DefaultFieldNameInferrer"

I try to create a dynamic request,
The code is like this:

`
QueryContainer filter = null;

filter = Filters.CreateFilter<objModel>(f => f.MY_PROPERTY == "blabla");

if (conditionA)
   filter = filter.AndFilteredOn<objModel>(f => f.MY_PROPERTY2 == "blablabla");

if (conditionB)
   filter = filter.AndFilteredOn<objModel>(f => f.MY_PROPERTY3 == "bla");


                   var node = new Uri(BaseService.ELASTICSEARCH_ENDPOINT);

                    var connectionPool = new SniffingConnectionPool(new[] { node });
                    var connectionSettings = new ConnectionSettings(connectionPool)
                               .DefaultFieldNameInferrer(p => p)
                               .DefaultTypeNameInferrer(p => p.Name);
   

                    ElasticClient elasticClient = new ElasticClient(connectionSettings);
                    
                    IEnumerable<objModel> resp = null;

                    resp = elasticClient.Search<objModel>
                        (s => s.Index(BaseService.ES_INDEX_NAME)
                            .Query(
                                q => q.ConstantScore
                                    (c => c.Filter(f => f.Bool(b => b.Must(m => filter))))
                                  )
                            .From(elemsToSkip)
                            .Take(maxResults)
                       )
                       .Hits
                       .Select(h => h.Source);

                   List<objModel> result = resp?.ToList();

`

**Comment by hoonzis** [comment]
Hi,

Seems @marchanddesable  is right, we are lowering firsts character when infering the fields name from property, which only works with the standard situation when CamelCase properties are transformed into "camelCase"fields.

I have looked into it and it seems that we should instead be using the fields inference available in NEST:
https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html

**Comment by filpen** [comment]
Thanks for the clarification @marchanddesable , I understand now. Yes @hoonzis it looks like we are doing it wrong :) It makes sense to fix it at least in the 2.* branch.

**Comment by marchanddesable** [comment]
Thank you for the help, 

I can't continue the work with this issue, so please let me know when you have updated FluentNest.

Thank you!

**Comment by hoonzis** [comment]
Hi I have merged a fix for this into master, not sure that I got 100% of this right, but at least Filtering is now working. Check this test, which has similar setup us your problem.

https://github.com/hoonzis/fluentnest/blob/master/FluentNest.Tests/PropertyNamesTests.cs

The latest nuget package should contain it, or just checkout master.
