### ISSUE TITLE
Please sign the assembly

### ISSUE THREAD

**Issue by bergdahl** [hoonzis/fluentnest#30]
People can't use the nuget package from a project that requires assembly signing.

**Comment by filpen** [comment]
Ah the good old debate. I think this is a good guideline to follow: https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/Documentation/project-docs/strong-name-signing.md#faq

You might want to consider using something like https://github.com/dsplaisted/strongnamer as a workaround.
