### ISSUE TITLE
nullable properties in conditions

### ISSUE THREAD

**Issue by us9898** [hoonzis/fluentnest#40]
public class Car
	{
                  public DateTime LastAccident { get; set; }
        }

 class search
    {
        public DateTime? DateSearch { get; set; }
    }

c=>c.LastAccident > search.D

fails in the method GetFieldNameFromMember,  
 var memberAccessor = binaryExpression.Left as MemberExpression ;  .. (filter.cs line 108)
var fieldName = GetFieldNameFromMember(memberAccessor);

throws exception in GetFieldNameFromMember  as memberAccessor resolves to null.
The  binaryExpression.Left  is {Convert(c.LastAccident)}.

**Comment by us9898** [comment]
thank you for looking into this issue.

I had another question, not exactly related to this.
If there is an array of nested objects in the document. 



like 
public class Car
{
    public List<Tyre> tyre{ get; set; }
}


public class Tyre{
  public string Company {get;set;}
   public string Size {get;set;}
}

Would it makes makes sense to write some thing like
Expression<Func<Car, bool>> nestedDocsQuery1 = x => x.Tyres.Any(y => y.size == 9 || y.size == 10 || y.size == 11);


changes can be in the method:
public static QueryContainer GenerateFilterDescription<T>(this Expression expression) where T:class{
.......
// additional condition
  if (expType == ExpressionType.Call)
	        {		     
		        return GenerateFilterDescription<T>((MethodCallExpression)expression);
	        }
}

 var firstArgument =(MemberExpression) expression.Arguments.First();
			    var secondArgument = expression.Arguments.Skip(1).First();
			    var methodInfo = expression.Method;

			    if (expression.Method.Name.ToLower().Equals("any"))
			    {
				    var fieldname = firstArgument.GetFieldNameFromMember();
				    var type = GetPropertyType(typeof(T), fieldname);

				    Type ex = typeof(Filters);
				    MethodInfo mi = ex.GetMethod("GenerateFilterDescription");
				    MethodInfo miConstructed = mi.MakeGenericMethod(type);
				    var filter =(QueryContainer) miConstructed.Invoke(null, new []{ secondArgument } );

				    var newFilter = new QueryContainerDescriptor<T>();
				    var newPartOfQuery = newFilter.Nested(descriptor => descriptor.Path(fieldname).Query(q=> filter));
				    return newPartOfQuery;

**Comment by filpen** [comment]
Yes, if you have a nested mapping I guess that would work. You just need to be careful because you are supporting a single method of the whole IEnumerable<T> interface and there could be the expectation that other methods would also work. As far as I understand though, judging by the fact that you are using reflection, you are implementing that in your own code so it should be a decent compromise.
