### ISSUE TITLE
In FuentNest 2.0 GetDictionary is not avaliable

### ISSUE THREAD

**Issue by existeundelta** [hoonzis/fluentnest#6]
var result = client.Search<Car>(sc => sc.Aggregations(agg => agg
    .SumBy(s => s.Price)
    .GroupBy(s => s.EngineType))
);

var carTypesDictionary = result.Aggs.GetDictioanry<Car,EngineType>(x => x.EngineType);

Cannot resolve simbol

**Comment by filpen** [comment]
Hi,

is "GetDictioanry" a typo in your actual code or it's just a typo in the sample code you posted? If you are using GetDictionary, you should specify the types, as in GetDictionary<Car,EngineType>. You can see an example of this in action in the test GetDictionaryFromGroupBy. Does this solve your issue?

**Comment by hoonzis** [comment]
Here is an examply that compiles:
https://dotnetfiddle.net/Wi8GR3

This uses the 1.* version of elasticsearch and fluentnest (as the 2.* is not available as nuget package), but the same compiles in the 2.* branch.
As well as @filpen said you can see example in the tests:
https://github.com/hoonzis/fluentnest/blob/29d4295b61418c572aec0243d1fb1abf7b70e896/Tests/GroupByTests.cs

**Comment by existeundelta** [comment]
Thanks!
@filpen yes, sorry, there was a typo in the post, but also in the Wiki! :dancer: (I edit it ;))
Thanks!!!  @filpen & @hoonzis amazing job!

**Comment by existeundelta** [comment]
Still it doesn't work, 
it gives me:
"Method not found: 'Nest.Bucket`1<Nest.KeyedBucket> Nest.AggregationsHelper.Terms(System.String)'."
in FluentNest.GroupBys.GetDictionary[T,V](AggregationsHelper aggs, Expression`1 fieldGetter)

i do something like this:

QueryContainer queryFromFilter = CreateQueryFromFilter();

            IAggregationContainer aggregationContainerDescriptor = new AggregationContainerDescriptor<EntitieType>()
                                    .SumBy<EntitieType>(x => x.Count)
                                    .GroupBy(x => x.Field1);
                            
            SearchDescriptor<EntitieType> search = new SearchDescriptor<EntitieType>()
                                        .Size(0)
                                        .SearchType(SearchType.Count)
                                        .Query(q => queryFromFilter)
                                        .Aggregations(agg => aggregationContainerDescriptor);

            ISearchResponse<EntitieType> result = Index.Client(IndexName).Search<EntitieType>(search);

            IDictionary<decimal, KeyedBucket> groups =  result.Aggs.GetDictionary<EntitieType, decimal>(x => x.Field1);

Does it work only with enums?

**Comment by hoonzis** [comment]
It should work for all basic types, but we probably do not have a test for decimal yet. I will look at it and let you know. It is possible that the issue in on our side.

**Comment by existeundelta** [comment]
really first I used <EntitieType, int>, so it's rare, I will also try to debug it, because now I just reference the dll

**Comment by existeundelta** [comment]
Well, it seams that the problem is because we have diferent Nest.dll, I really don't understand, because I got it from nuget , but i reference my Nest.dll, in FluentNest and some Errors appear

**Comment by hoonzis** [comment]
that is quite strange. FluentNest branch 2.0.0 needs a NEST >= 2.0.0 so which version of Nest.dll are you using?

We currently publish only a nuget package which is compatible with ElasticSearch 1.7.* and greater. You can see it's dependencies on NEST < 2. https://www.nuget.org/packages/FluentNest/1.0.125
We will publish a nuget FluentNest 2.0.* soon, but it has not been done. So if you need to support ElasticSearch 2, than you have add FluentNest project to your solution manually, which I suppose is what you are doing, right?

**Comment by existeundelta** [comment]
Yes I'm using NEST>=2.0.0, what I think is that "mine" Nest.dll and "your" Nest.dll are not exactly the same

**Comment by existeundelta** [comment]
In FluentNest the nuget package is Nest2.0.0.alpha, and now the stable version of Nest is 2.3.2, and it seams things have changed

**Comment by existeundelta** [comment]
if I do it correcctly, for example therer are this errors:

Severity	Code	Description	Project	File	Line
Error	CS1503	Argument 1: cannot convert from 'Nest.ValueAggregate' to 'ValueMetric'	FluentNest	\FluentNest\StatisticsGetters.cs	76


Severity	Code	Description	Project	File	Line
Error	CS0246	The type or namespace name 'ValueMetric' could not be found (are you missing a using directive or an assembly reference?)	FluentNest	FluentNest\StatisticsGetters.cs	51


Severity	Code	Description	Project	File	Line
Error	CS1061	'TermsAggregate' does not contain a definition for 'Items' and no extension method 'Items' accepting a first argument of type 'TermsAggregate' could be found (are you missing a using directive or an assembly reference?)	FluentNest	FluentNest\StatisticsGetters.cs	101

**Comment by existeundelta** [comment]
I see the updates, but with the update I still get the errors

**Comment by hoonzis** [comment]
yes, @filpen has been working on some fixes. We will be able to fix that today probably. Honestly since we are not using ES 2 in production, we did not nested the 2.0.0 branch very well (besides our unit tests).

**Comment by existeundelta** [comment]
besides above errors also 

Severity	Code	Description	Project	File	Line
Error	CS1061	'MultiBucketAggregate<HistogramBucket>' does not contain a definition for 'Items' and no extension method 'Items' accepting a first argument of type 'MultiBucketAggregate<HistogramBucket>' could be found (are you missing a using directive or an assembly reference?)	FluentNest	FluentNest\Filters.cs	103

and

HistogramItem could not be found

**Comment by existeundelta** [comment]
ok, thanks!

**Comment by existeundelta** [comment]
I upload a fix to https://github.com/existeundelta/fluentnest

**Comment by hoonzis** [comment]
That look pretty good, we are doing some cleanup in the mean-time: we moved to paket for references management and we are trying to script the installation of elasticsearch 2 on appveyor build server.
Once we are done you could probably rebase your branch and then create a pullrequest that we incorporate in our 2.0.0 branch

**Comment by existeundelta** [comment]
Thanks!

**Comment by hoonzis** [comment]
Hi, I have finally took some time to fix the 2.0.0 branch, it includes your corrections as well.
Could you please rebase your branch on 2.0.0 (you might get some conflicts) or just checkout fresh and verify that all is working fine for you?

We now have a automatic build with tests for the 2.0.0 branch as well. https://ci.appveyor.com/project/hoonzis/fluentnest

**Comment by hoonzis** [comment]
Hi we did finally a bit more of cleanup in order to reflect the current versions of ES and also of Nest we now have:

master branch - compatible with ES ~> 2
1.0.0 branch - tested with ES ~> 1.7 & <~ 2

we also have a nuget package for 2 based version

So your 2.0.0 branch could be now rebased from master. But unless you have done a lot of development, you should just checkout master - all should now be working fine for you.

**Comment by existeundelta** [comment]
Ok thanks! :) :+1:
